### ISSUE TITLE
Incorrect register operands for jalr instruction

### ISSUE THREAD

**Issue by micahswitzer** [mumbel/ghidra_riscv#4]
In the process of implementing the `R_RISCV_CALL` relocation, I noticed that the register operands for the `jalr` instruction seem to be swapped.

The disassembly from the processor module looks like this (with my relocations applied):
![image](https://user-images.githubusercontent.com/6128108/97820351-cb29c700-1c7b-11eb-839f-ea451491bc7a.png)
 
And the disassembly from `objdump` looks like this:
![image](https://user-images.githubusercontent.com/6128108/97820409-05936400-1c7c-11eb-8f9c-2454f0c715b0.png)

I know the registers are actually swapped because in the decompilation view, Ghidra shows the called address parameterized off of `t6` instead of `ra`:
![image](https://user-images.githubusercontent.com/6128108/97820657-28724800-1c7d-11eb-9cac-d4522c4e88ae.png)

I briefly tried looking through the pcode to see if I could spot anything obvious, but I'm not very good with pcode and was not able to make much sense of it. The object file I'm looking at can be found [here](https://github.com/pine64/bl602-re/blob/master/libatcmd/at_command.o), and the disassembly [here](https://github.com/pine64/bl602-re/blob/master/libatcmd/at_command.o.s).

**Comment by mumbel** [comment]
That's odd, wonder why binutils isn't using the syntax from the manual.  I'm getting  `jalr ra, -224(t6)` with no pseudo and `jalr -224(t6)` with.  I'll look a bit more into binutils src.

Just to be clrear, you're not attempting to edit the sla file right, only .sinc files?

edit:  guess you meant at_command.o not common?

**Comment by micahswitzer** [comment]
I haven't tried to modify any of the pcode at all. I've only been touching the Java code.

**Comment by micahswitzer** [comment]
> edit: guess you meant at_command.o not common?

Sorry, yes. I fixed the original comment.

**Comment by mumbel** [comment]
My build must have been in a bad state the last couple of days, I just got it printing all those warnings for unimpl relocation, not sure what I did.   I was just asking about sinc files because you had mentioned pcode, just making sure if you were making changes there and not the generated file.

So that's is kind of surprising the relocation would change  `jalr ra, ra, 0x0` into `t6` and would guess that's the issue you're seeing, not out of order operands.  Are you sure you're only touching bits 20-31, what operations are you using to touch bits 15-19?

**Comment by micahswitzer** [comment]
Yeah, this is more strange than I thought. Here is the code I was using:
```java
case RISCV_ElfRelocationConstants.R_RISCV_CALL:
	// PC-relative call MACRO call,tail (auipc+jalr pair)
	// symbol + addend - position
	// make an assumption for now.
	long sa = symbolValue + addend - offset;
	long hi20 = (sa + 0x800) >> 12;
	sa = symbolValue + addend - relocationAddress.add(4).getOffset();
	long lo12 = sa - (hi20 << 12);
	//hi20 = ((symbol_address - hi20_reloc_offset + 0x800) >> 12);
	//lo12 = symbol_address - hi20_reloc_offset - (hi20 << 12);
	value32 = memory.getInt(relocationAddress, true);
	value32 |= (int)(hi20 & 0xfffff);
	memory.setInt(relocationAddress, value32, true);
	value32 = memory.getInt(relocationAddress.add(4), true);
	value32 |= (int)(lo12 & 0xfff);
	memory.setInt(relocationAddress.add(4), value32, true);
	markAsWarning(program, relocationAddress, "R_RISCV_CALL", symbolName, symbolIndex,
			String.format("TODO, needs better implementation. sa = %08x, hi20 = %08x, lo12 = %08x", sa, hi20, lo12), elfRelocationContext.getLog());
	break;
```

It's pretty gross at the moment, but I'm very confident I'm only touching bits 20-31 like you said. Is it possible that it's decoding the register from the wrong bits?

**Comment by micahswitzer** [comment]
Found the issue. It turns out that the instructions are stored little-endian for some reason. That was throwing me off and I was applying the relocation incorrectly. Once I fixed that, the relocation worked as expected!
