### ISSUE TITLE
csrrci breaks decompilation

### ISSUE THREAD

**Issue by stschake** [mumbel/ghidra_riscv#5]
csrrci (and I'd assume other csrr* instructions) seem to break decompilation. Example assembly:

    2300e4a2 73 70 04 30     csrrci     zero,mstatus,0x8
    2300e4a6 b7 c7 01 42     lui        a5,0x4201c
    2300e4aa 93 87 87 c5     addi       a5,a5,-0x3a8
    2300e4ae 98 43           c.lw       a4,0x0(a5=>ke_env)                               
    2300e4b0 49 8f           c.or       a4,event
    2300e4b2 98 c3           c.sw       a4,0x0(a5=>ke_env)                               
    2300e4b4 73 60 04 30     csrrsi     zero,mstatus,0x8
    2300e4b8 82 80           ret

This seems to be a pretty common construct for a critical area. I've attached the Ghidra debug XML. Sorry, I haven't looked into how to properly debug Ghidra decompilation yet, so it only shows "Exception while decompiling 2300e4a2: Decompiler process died" right now.

[ke_evt_set.xml.txt](https://github.com/mumbel/ghidra_riscv/files/5483113/ke_evt_set.xml.txt)

**Comment by mumbel** [comment]
Ah, it's looks like I need better logic/handling for the write to zero

**Comment by stschake** [comment]
The rd = csr was a good shout, commenting that out makes the decompilation work. It doesn't emit any code for the csrr instructions, but then I'm not sure how that is supposed to show up in the decompilation output in the first place.

**Comment by mumbel** [comment]
@stschake   thanks for verifying that.  looking into a real solution now.

**Comment by mumbel** [comment]
@stschake  hopefully didn't break anything in the process of copying out of ghidra repo, but just pushed b306037bf877ade7e0bd735248ed37404574193a  which should fix this and a few others minor changes

**Comment by stschake** [comment]
@mumbel thanks, the issue is gone in the latest version!
